# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ucgen_cizdirme.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(621, 485)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ustFrame = QtWidgets.QFrame(Dialog)
        self.ustFrame.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border-radius:10px")
        self.ustFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ustFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ustFrame.setObjectName("ustFrame")
        self.kenarUzunluguLineEdit = QtWidgets.QLineEdit(self.ustFrame)
        self.kenarUzunluguLineEdit.setEnabled(True)
        self.kenarUzunluguLineEdit.setGeometry(QtCore.QRect(80, 40, 461, 41))
        self.kenarUzunluguLineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.kenarUzunluguLineEdit.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.kenarUzunluguLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.kenarUzunluguLineEdit.setPlaceholderText("")
        self.kenarUzunluguLineEdit.setClearButtonEnabled(True)
        self.kenarUzunluguLineEdit.setObjectName("kenarUzunluguLineEdit")
        self.baslatButon = QtWidgets.QPushButton(self.ustFrame)
        self.baslatButon.setGeometry(QtCore.QRect(400, 140, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.baslatButon.setPalette(palette)
        self.baslatButon.setAutoFillBackground(False)
        self.baslatButon.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.baslatButon.setAutoRepeat(False)
        self.baslatButon.setDefault(False)
        self.baslatButon.setFlat(False)
        self.baslatButon.setObjectName("baslatButon")
        self.verticalLayout.addWidget(self.ustFrame)
        self.altFrame = QtWidgets.QFrame(Dialog)
        self.altFrame.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"border-radius:10px")
        self.altFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.altFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.altFrame.setObjectName("altFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.altFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.altSolFrame = QtWidgets.QFrame(self.altFrame)
        self.altSolFrame.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.altSolFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.altSolFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.altSolFrame.setObjectName("altSolFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.altSolFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.hizLabel = QtWidgets.QLabel(self.altSolFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.hizLabel.setFont(font)
        self.hizLabel.setObjectName("hizLabel")
        self.gridLayout.addWidget(self.hizLabel, 0, 0, 1, 1)
        self.aciLabel = QtWidgets.QLabel(self.altSolFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.aciLabel.setFont(font)
        self.aciLabel.setObjectName("aciLabel")
        self.gridLayout.addWidget(self.aciLabel, 1, 0, 1, 1)
        self.hizGostergeLabel = QtWidgets.QLabel(self.altSolFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.hizGostergeLabel.setFont(font)
        self.hizGostergeLabel.setObjectName("hizGostergeLabel")
        self.gridLayout.addWidget(self.hizGostergeLabel, 0, 1, 1, 1)
        self.aciGostergeLabel = QtWidgets.QLabel(self.altSolFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.aciGostergeLabel.setFont(font)
        self.aciGostergeLabel.setObjectName("aciGostergeLabel")
        self.gridLayout.addWidget(self.aciGostergeLabel, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.altSolFrame)
        self.altSagFrame = QtWidgets.QFrame(self.altFrame)
        self.altSagFrame.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.altSagFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.altSagFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.altSagFrame.setObjectName("altSagFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.altSagFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bilgilendirmeLabel = QtWidgets.QLabel(self.altSagFrame)
        self.bilgilendirmeLabel.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bilgilendirmeLabel.setFont(font)
        self.bilgilendirmeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bilgilendirmeLabel.setObjectName("bilgilendirmeLabel")
        self.gridLayout_2.addWidget(self.bilgilendirmeLabel, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.altSagFrame)
        self.verticalLayout.addWidget(self.altFrame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.kenarUzunluguLineEdit.setText(_translate("Dialog", "üçgenin kenar uzunluğunu giriniz..."))
        self.baslatButon.setText(_translate("Dialog", "BAŞLAT"))
        self.hizLabel.setText(_translate("Dialog", "HIZ"))
        self.aciLabel.setText(_translate("Dialog", "AÇI"))
        self.hizGostergeLabel.setText(_translate("Dialog", "N/A"))
        self.aciGostergeLabel.setText(_translate("Dialog", "N/A"))
        self.bilgilendirmeLabel.setText(_translate("Dialog", "Komut Bekleniyor..."))
